name: "receberEmail"
description: "Aplicação para envio de Email Corporativo"
version: "0.0.1-SNAPSHOT"

spring:
  profiles:
    active: ${PROFILE}
  activemq:
    broker-url: ${emailCorp_receber_urlBroker}
    user: ${emailCorp_receber_usrBroker}   
    password: ${emailCorp_receber_pwdBroker} 

server:
  address: 0.0.0.0
  port: 8091
  servlet:
    contextPath: /enviarMail            

springdoc:
  show-actuator: false
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

auth:
  codigoAplicacao: AUTORIZADOR-SERVICE      
  baseUrl: ${emailCorp_receber_authUrl}
  token-autenticacao: ${emailCorp_receber_authToken}
  
app:
  dirAnexos: ${emailCorp_receber_dirAnexos}    