name: "receberEmail"
description: "Aplicação para envio de Email Corporativo"
version: "1.0.0"

spring:
  profiles:
    active: ${PROFILE}
  activemq:
    broker-url: ${urlBroker}
    user: ${usrBroker}   
    password: ${pwdBroker} 

server:
  address: 0.0.0.0
  port: 8091
  servlet:
    contextPath: /senderMail            

springdoc:
  show-actuator: false
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

auth:
  codigoAplicacao: AUTORIZADOR-SERVICE      
  baseUrl: ${authUrl}
  token-autenticacao: ${authToken}
    
logging:
  config: ${arqConf}      
  
app:
  dirAnexos: ${dirAnexos}    