#Open API - Swagger
name: "receberEmail"
description: "Aplicação para envio de Email Corporativo"
version: "1.0.0"

spring:
  profiles:
    active: local
  activemq:
    broker-url: tcp://drhel8labplat001v.sefnet.rj:61616
    password: 123456
    user: emailCorp    
  mail:
    host: smtp2.sefnet
    username: mrepereira
    password: 200867Mrp##
    port: 25
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          ehlo: false
          starttls:
            enable: false

server:
  address: 0.0.0.0
  port: 8091
  servlet:
    contextPath: /senderMail            
enexo:
  path: /var/email/anexos

cors:
  mapping: "/**"
  origins: "**"
  methods: "*"
  headers: "*"

springdoc:
  show-actuator: false
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false


auth:
  codigoAplicacao: AUTORIZADOR-SERVICE      